debugMode: true
database:
  connectionString: ""
  database: "rocketchat"
source:
  type: "FileSystem"
  FileSystem:
    location: ""
tempFileLocation: "files"
destination:
  type: "AmazonS3"
  AmazonS3:
    endpoint: ""
    bucket: ""
    accessId: ""
    accessKey: ""
    region: "eu"
    useSSL: true
